lok:
  issuer: herre
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3zKYtsPl/wsTtX4XQRtBnaTYYXGzqF8uhAourwqvWYPMnQlVbSJGZquVkmljFnRKg1FjOmoEsjIvb9tBtyZuW+oWL06aqArLm2kcCbPofYN8mJnoQdtAxssnJz02gkIYfbFUy/ImBWWq3xQjbleNtN8qGPGaYbo3BIzZv1zwZIddta0MJhBGlGhUO1LsookU6k0OaZcFg1xjUFZgkgTm7DNWUkuEBJwtGvI6W6IF0e2KAXkgp/c77p+5/ZqXwa694+Uoz36Dqsffjho2FtfLwFUfsFvIkB40Pwzd/2Uie9b5W8ocXou3S71+6jgeQZqsB+STnBX/X4Uh7d5uiPSoH
port: 8070
postgres:
  db_name: fluss_db
  host: daten
  password: 6398045f7711b517ac0aa3c7e6b77a63
  port: 5432
  user: arkitekt
redis:
  host: redis
  port: 6379
minio:
  access_key: kBcG6sCIlQvOWPOpzJhu
  buckets:
    - zarr
    - media
  host: minio
  port: 9000
  protocol: http
  secret_key: FjiprDl3qHwIMR7azM2M
  bucket: flussmedia
server:
  admin:
    email: johannes.roos@u-bordeaux.fr
    password: roos
    username: admin
  debug: true
  hosts:
    - "*"
  secret_key: ymlz&s8-xf)*25t=yid!5obz7go4-9jzo!^72zsfum6bg7@j&p
