# Generated by Django 6.0.6 on 2026-09-28 12:05

import django.db.models.deletion
import django_choices_field.fields
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('reaktion', '0003_title_embeddings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=256, editable=False, help_text='Unit-length embedding of name + description, by the model named in embedding_model; NULL when there is no text to embed', null=True)),
                ('embedding_model', models.CharField(blank=True, default='', editable=False, help_text='The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then', max_length=200)),
                ('title', models.CharField(max_length=10000, null=True)),
                ('description', models.CharField(blank=True, max_length=50000, null=True)),
                ('lineage', models.UUIDField(default=uuid.uuid4, help_text='Shared by every version of the same flow')),
                ('source', models.TextField()),
                ('entrypoint', models.CharField(default='main', max_length=1000)),
                ('args', models.JSONField(default=list, help_text="The ArgPorts derived from the entrypoint's signature")),
                ('returns', models.JSONField(default=list, help_text="The ReturnPorts derived from the entrypoint's signature")),
                ('manifest', models.JSONField(default=list, help_text='Every action the source may call, under the name it is injected as')),
                ('runtime', models.CharField(help_text='The executor runtime (interpreter + helpers) the source was validated against', max_length=1000)),
                ('status', django_choices_field.fields.TextChoicesField(choices=[('DRAFT', 'DRAFT (Stored, not registered as an action)'), ('PUBLISHED', 'PUBLISHED (Registered as an action)'), ('ARCHIVED', 'ARCHIVED (No longer registered; kept for its runs)')], default='DRAFT', max_length=100)),
                ('hash', models.CharField(help_text='sha256 over source, entrypoint, manifest and runtime', max_length=64)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='python_flows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('pinned_by', models.ManyToManyField(blank=True, related_name='pinned_python_flows', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='reaktion.pythonflow')),
            ],
        ),
        migrations.CreateModel(
            name='PythonRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('task_id', models.CharField(max_length=1000)),
                ('status', django_choices_field.fields.TextChoicesField(choices=[('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='RUNNING', max_length=100)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reaktion.pythonflow')),
                ('pinned_by', models.ManyToManyField(blank=True, related_name='pinned_python_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pythonflow',
            index=models.Index(fields=['embedding_model'], name='pyflow_emb_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='pythonflow',
            constraint=models.UniqueConstraint(fields=('organization', 'lineage', 'hash'), name='pyflow_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='pythonrun',
            constraint=models.UniqueConstraint(fields=('flow', 'task_id'), name='pyrun_unique_task'),
        ),
    ]
