# Generated by Django 3.1.7 on 2021-03-05 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import namegenerator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkitekt_id', models.CharField(help_text='The identifier on the Arkitekt platform', max_length=1000)),
                ('name', models.CharField(help_text='The name of this Flow', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlowPod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkitekt_pod', models.CharField(help_text='The Corresponding Pod in Arnheim', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkitekt_id', models.CharField(help_text='The Template this one belongs two (Arkitekt identifier)', max_length=4000)),
                ('port_id', models.CharField(help_text='The PortTemplate this one belongs two (Arkitekt identifier)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0alpha', max_length=100)),
                ('name', models.CharField(default=namegenerator.gen, max_length=100, null=True)),
                ('diagram', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='Add a Description', max_length=50000, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(help_text='Associated Node for this', null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flownode')),
                ('pod', models.ForeignKey(help_text='Associated Node for this', null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flowpod')),
                ('template', models.ForeignKey(help_text='Associated template for this', null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flowtemplate')),
            ],
        ),
    ]
