# Generated by Django 3.1.7 on 2021-03-29 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graph',
            name='node',
            field=models.ForeignKey(help_text='Associated Node for this', null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flownode'),
        ),
        migrations.AddField(
            model_name='graph',
            name='pod',
            field=models.ForeignKey(help_text='Associated Node for this', null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flowpod'),
        ),
        migrations.AddField(
            model_name='graph',
            name='template',
            field=models.ForeignKey(help_text='Associated template for this', null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flowtemplate'),
        ),
    ]
