# Generated by Django 3.2.18 on 2023-03-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runevent',
            name='caused_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
