# Generated by Django 3.1.7 on 2021-03-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='arkitekt_id',
            field=models.CharField(help_text='The identifier on the Arkitekt platform', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='flowpod',
            name='arkitekt_pod',
            field=models.CharField(help_text='The Corresponding Pod in Arnheim', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='flowtemplate',
            name='arkitekt_id',
            field=models.CharField(help_text='The Template this one belongs two (Arkitekt identifier)', max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name='flowtemplate',
            name='port_id',
            field=models.CharField(help_text='The PortTemplate this one belongs two (Arkitekt identifier)', max_length=100, unique=True),
        ),
    ]
