# Generated by Django 3.2.18 on 2023-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='snapshot_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
