# Generated by Django 3.1.7 on 2021-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkitekt_pod', models.CharField(help_text='The Corresponding Pod in Arnheim', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='graph',
            name='node',
            field=models.CharField(blank=True, help_text='The Node this one belongs two', max_length=1000, null=True),
        ),
    ]
