# Generated by Django 3.2.16 on 2022-12-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20221213_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactivetemplate',
            old_name='args',
            new_name='constants',
        ),
    ]
