# Generated by Django 3.1.7 on 2021-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20210301_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='port_id',
            field=models.CharField(default=123, help_text='The PortTemplate this one belongs two (Arkitekt identifier)', max_length=100),
            preserve_default=False,
        ),
    ]
