# Generated by Django 3.2.10 on 2022-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20220331_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='diagram',
            new_name='edges',
        ),
        migrations.AddField(
            model_name='flow',
            name='nodes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
