# Generated by Django 3.2.19 on 2023-05-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_run_snapshot_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('provision', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot_interval', models.IntegerField(blank=True, null=True)),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='flow.flow')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('t', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='flow.condition')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('t', models.IntegerField()),
                ('source', models.CharField(max_length=1000)),
                ('event', models.CharField(max_length=1000)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='flow.condition')),
                ('snapshot', models.ManyToManyField(related_name='events', to='flow.ConditionSnapshot')),
            ],
        ),
    ]
