# Generated by Django 3.1.7 on 2021-03-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20210305_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowtemplate',
            name='port_id',
        ),
    ]
