# Generated by Django 3.2.19 on 2023-05-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_condition_conditionevent_conditionsnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionevent',
            name='t',
        ),
        migrations.RemoveField(
            model_name='conditionsnapshot',
            name='t',
        ),
    ]
