# Generated by Django 3.2.10 on 2022-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20220331_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='edges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='nodes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
