# Generated by Django 3.2.10 on 2022-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20220331_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='graph',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
