# Generated by Django 3.2.19 on 2023-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20230518_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionevent',
            name='event',
        ),
        migrations.AddField(
            model_name='conditionevent',
            name='value',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
