# Generated by Django 3.2.10 on 2022-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_flow_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='brittle',
            field=models.BooleanField(default=False, help_text='Is this a brittle flow? aka. should the flow fail on any exception?'),
        ),
    ]
