# Generated by Django 3.2.19 on 2023-05-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20230518_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionevent',
            name='state',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
