# Generated by Django 3.2.19 on 2023-05-25 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0006_conditionevent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condition',
            name='created_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_created_through', to='lok.lokclient'),
        ),
        migrations.AddField(
            model_name='condition',
            name='created_while',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the position', related_name='pinned_conditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flow',
            name='created_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_created_through', to='lok.lokclient'),
        ),
        migrations.AddField(
            model_name='flow',
            name='created_while',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the position', related_name='pinned_flows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='run',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='run',
            name='created_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_created_through', to='lok.lokclient'),
        ),
        migrations.AddField(
            model_name='run',
            name='created_while',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the position', related_name='pinned_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_created_through', to='lok.lokclient'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_while',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the position', related_name='pinned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reactivetemplate',
            name='implementation',
            field=models.CharField(choices=[('ZIP', 'ZIP (Zip the data)'), ('COMBINELATEST', 'COMBINELATEST (Combine values with latest value from each stream)'), ('WITHLATEST', 'WITHLATEST (Combine a leading value with the latest value)'), ('BUFFER_COMPLETE', 'BUFFER_COMPLETE (Buffer values until complete is retrieved)'), ('BUFFER_UNTIL', 'BUFFER_UNTIL (Buffer values until signal is send)'), ('CHUNK', 'CHUNK (Chunk the data)'), ('SPLIT', 'SPLIT (Split the data)'), ('OMIT', 'OMIT (Omit the data)'), ('ENSURE', 'ENSURE (Ensure the data (discards None in the stream))'), ('GATE', 'GATE (Gate the data, first value is gated, second is gate)'), ('TO_LIST', 'TO_LIST (Convert to list)'), ('FOREACH', 'FOREACH (Foreach element in list)'), ('IF', 'IF (If condition is met)'), ('AND', 'AND (AND condition)'), ('ALL', 'ALL (establish if all values are Trueish)')], default='ZIP', max_length=1000, unique=True),
        ),
    ]
