# Generated by Django 3.2.10 on 2022-06-29 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_run_runlog_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='assignation',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
