# Generated by Django 3.2.19 on 2023-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_workspace_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
