# Generated by Django 3.2.10 on 2022-07-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_auto_20220629_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='flow.flow'),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='flow.run'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='flow.run'),
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('type', models.CharField(choices=[('NEXT', 'NEXT (Value represent Labels)'), ('ERROR', 'Error (Value represent Intensity)'), ('COMPLETE', 'COMPLETE (First three channel represent RGB)'), ('UNKNOWN', 'UNKNOWN (Value represent Intensity)')], default='UNKNOWN', max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('handle', models.CharField(max_length=1000)),
                ('value', models.JSONField(blank=True, default=[], null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='flow.run')),
            ],
        ),
    ]
