# Generated by Django 3.2.19 on 2023-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0009_alter_run_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
