# Generated by Django 3.2.10 on 2022-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0009_auto_20220705_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='runevent',
            name='snapshot',
            field=models.ManyToManyField(related_name='events', to='flow.Snapshot'),
        ),
    ]
