# Generated by Django 3.2.10 on 2022-07-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_runevent_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='state',
        ),
    ]
