# Generated by Django 3.2.10 on 2022-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_remove_snapshot_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='runevent',
            name='t_loop',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
