# Generated by Django 3.2.10 on 2022-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0012_runevent_t_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='t_loop',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
