# Generated by Django 3.2.10 on 2022-07-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_snapshot_t_loop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runevent',
            old_name='t_loop',
            new_name='t',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='t_loop',
            new_name='t',
        ),
    ]
