# Generated by Django 3.2.15 on 2022-08-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0014_auto_20220705_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='screenshot',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
