# Generated by Django 3.2.15 on 2022-08-17 17:24

from django.db import migrations, models
import flow.storage
import namegenerator


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0015_flow_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=namegenerator.gen, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='graph',
            name='creator',
        ),
        migrations.AddField(
            model_name='flow',
            name='hash',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='screenshot',
            field=models.ImageField(null=True, storage=flow.storage.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='runevent',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('graph', 'hash'), name='Equal Reservation on this App by this Waiter is already in place'),
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
