# Generated by Django 3.2.15 on 2022-08-17 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0016_auto_20220817_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='diagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.diagram'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='hash',
            field=models.CharField(default=uuid.uuid4, max_length=4000),
        ),
    ]
