# Generated by Django 3.2.15 on 2022-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0017_auto_20220817_1725'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flow',
            name='Equal Reservation on this App by this Waiter is already in place',
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('diagram', 'hash'), name='Equal Reservation on this App by this Waiter is already in place'),
        ),
    ]
