# Generated by Django 3.2.15 on 2022-08-17 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0018_auto_20220817_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='description',
            field=models.CharField(blank=True, default='Add a Dessscription', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='diagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='flow.diagram'),
        ),
    ]
