# Generated by Django 3.2.15 on 2022-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0020_diagram_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactiveNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('implementation', models.CharField(choices=[('ZIP', 'ZIP (Zip the data)'), ('CHUNK', 'CHUNK (Chunk the data)')], default='ZIP', max_length=1000)),
            ],
        ),
    ]
