# Generated by Django 3.2.15 on 2022-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0021_reactivenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivenode',
            name='constream',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='reactivenode',
            name='defaults',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reactivenode',
            name='instream',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='reactivenode',
            name='outstream',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
