# Generated by Django 3.2.15 on 2022-08-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0022_auto_20220819_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReactiveNode',
            new_name='ReactiveTemplate',
        ),
    ]
