# Generated by Django 3.2.15 on 2022-09-24 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0023_rename_reactivenode_reactivetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reactivetemplate',
            name='implementation',
            field=models.CharField(choices=[('ZIP', 'ZIP (Zip the data)'), ('COMBINELATEST', 'COMBINELATEST (Combine values with latest value from each stream)'), ('WITHLATEST', 'WITHLATEST (Combine a leading value with the latest value)'), ('BUFFER_COMPLETE', 'BUFFER_COMPLETE (Buffer values until complete is retrieved)'), ('BUFFER_UNTIL', 'BUFFER_UNTIL (Buffer values until signal is send)'), ('CHUNK', 'CHUNK (Chunk the data)'), ('SPLIT', 'SPLIT (Split the data)'), ('OMIT', 'OMIT (Omit the data)'), ('TO_LIST', 'TO_LIST (Convert to list)')], default='ZIP', max_length=1000),
        ),
    ]
